### ISSUE TITLE
[Change Proposal] Remove release tag from packages

### ISSUE THREAD

**Issue by jsoriano** [elastic/package-spec#225]
There is currently a partial overlap in different features regarding the stability level of a package, that uses to bring confusion to integration developers and users:
* `release` label in manifests can be experimental/beta/ga.
* Semantic versioning, a package with a version >= 1.0.0 is (could be) considered "stable".
* There are three registries: snapshot/staging/production.

Apart of the overlap, there is no enforcement between these features, so it can be possible to find in the production repository a 1.0.0 package marked as experimental.

The proposal would be:
* Remove the `release` labels from the main manifest. To avoid breaking changes they could be marked as optional in the spec, and eventually be ignored everywhere, package registry API could do best-effort interpretation for old experimental-related queries.
* Pre-releases semver fields can be defined to release unstable versions. Packages stability (and supportability) would be determined only by their version, not from its origin. This implies the need of a change in a package to release it as stable, but this is ok, as this allow to introduce an approval step in the process.
* "Unstable" or experimental features could be still added to GA packages, but must be disabled by default. An experimental feature, causing an issue to a user of a GA package not interested in this feature should be considered a bug in the package. Release tag can still be used at the datastream level to mark datastreams or integration tiles as beta or experimental.
* Users can configure the source of packages, a single source can be configured now, but this may change in the future, the source doesn't determine the stability of a package.
* Users can optionally enable the use of pre-releases to use non-GA packages. Limited or no support level would be granted for these packages.
* Eventually snapshot and staging registries may be removed (https://github.com/elastic/package-storage/discussions/3666).

Some examples with this model:
* Package foo 0.5.0 wouldn't be considered stable, wherever it is published.
* Package bar 2.0.0 would be considered stable, and should be supported by their maintainers/owners.
* Package bar 2.1.0-beta wouldn't be considered stable, but a release candidate.

Discarded ideas:
* The registry that serves the package is relevant to its stability. In principle we are going to continue using the promotion model, and it can be safely assumed that the production registry contains more stable packages than the other ones. But consumers of packages (as Kibana/Fleet) shouldn't need to interpret the stability of packages from its origin ([comment](https://github.com/elastic/package-spec/issues/225#issuecomment-947479939)).
* Rejection of "unstable" packages in the production repository should be enforced (consequence of previous comment).
* Removal of the `release` tag at the datastream level delayed as it belongs to a broader discussion about how to tag experimental/beta features in GA packages.

## Required changes

- [x] Integrations: review consistency in the use of semver and the release tag.
  - [x]  `security_detection_engine` mislabeled in 7.x https://github.com/elastic/package-registry/issues/793.
  - [x] `apm` always uses `release: ga`, even for non-ga versions https://github.com/elastic/apm-server/pull/7792.
- [x] package-spec: Deprecate `release`, extend documentation of `version` to describe the use of pre-release semver fields.
  - [x] https://github.com/elastic/package-spec/pull/256 
- [x] elastic-package: Review uses of the [release](https://github.com/elastic/elastic-package/search?l=Go&q=release) flag and update documentation.
  - [x] https://github.com/elastic/elastic-package/pull/647
  - [x] https://github.com/elastic/integrations/pull/2651
- [x] package-registry: Add support for a `/search` argument that lists packages with pre-release semver fields, disable it by default or depending on a flag, and try to keep compatibility with current API arguments related to versioning (`experimental`...).
  - [x] https://github.com/elastic/package-registry/pull/785 
- [x] ~~package-storage/distribution: If a flag is added to control this behaviour, decide the default option for each registry.~~ Not needed, currently kibana always use `experimental=true`.
- [ ] fleet: Add a configuration toggle to enable the search installation of pre-release packages.
  - [ ] https://github.com/elastic/kibana/issues/122973
- [x] external documentation: Review how these changes affect external integrations documentation.

**Comment by ruflin** [comment]
Lets focus for a moment on one vs multiple registries. There is the registry we run and there are going to be the registries that are run by users. Likely the registries run by users could also have additional packages inside at one point. These could be prerelease or GA. Requiring multiple registries for prerelease packages seems to put some limitations in that are not necessarily required. My take take is we should allow prerelease packages in the production registry.

In Fleet today we allow a single registry. You can point it to the production, testing, your own but not multiple registries. This keeps things simple for Fleet. One source of truth, no conflicting packages, only one remote request for search etc. If possible, it is a model I would like to keep for simplicity reasons. But assuming at some point we would allow pointing users to multiple registries, it would be likely n registries. And it would not only be for beta vs GA but different packages. And each of these registries could contain beta packages. Here again, we are back to each registry itself should support prerelease packages.

One of the reasons for the snapshot registry we have today was also to new registry releases out in the wild to make sure we don't break anything. But the value of this has decreased over time as the package-registry has become more stable and the test suite increased. 

I'm more and more leaning in the direction there should be likely a single registry and prereleases also go into it. This has at least 2 requirements:

* Unreleased packages can be cleaned up. For this to work, Kibana must cache these packages locally to make sure things don't break 
* Dockerfile does not contain the packages directly as otherwise it will keep growing.

**Comment by jsoriano** [comment]
Updated description after the latest comments.

**Comment by simitt** [comment]
Adding some use case regarding the topic of one vs. multiple registries:
We have a couple of packages that follow stack versioning (for example apm). During the dev process, we need to be able to publish a pre-release package for the upcoming release multiple times. Otherwise any features depending on the changes would only be testable with local registries during the dev cycle, which is not practical for automated tests and for cross-team collaboration. 
So far we are overwriting the package with the same version on snapshot/staging registries, but we absolutely avoid doing this on production, and only release the production package close to the stack release date. If we end up having only one registry at some point, we would probably need to publish with pre-release versions in production (for example: `8.2.2-rc3`). In this case we need to be absolutely certain that such pre-release packages are never used in users production environments.

**Comment by mtojek** [comment]
The issue I linked above shows some use cases for the release tag and presentation in docs. Let's keep in mind too.

**Comment by mtojek** [comment]
@simitt 

> So far we are overwriting the package with the same version on snapshot/staging registries, but we absolutely avoid doing this on production, and only release the production package close to the stack release date. I

This is an anti-pattern and you shouldn't follow this path at all. The endpoint team creates new revisions with release tags, for example: 1.2.3-dev1, 1.2.3-dev2, 1.2.3-dev3, 1.2.3. Revisions marked with "devX" are subjected to QA tests.

BTW we are actively working on signing package revisions and forbidding direct pushes to the Package Storage, so you will need to address these problems in the future.

**Comment by jsoriano** [comment]
> In this case we need to be absolutely certain that such pre-release packages are never used in users production environments.

Regarding this, this would be covered by the proposal, even with a single repository. A package that follows stack versioning, for example for 8.2.2, could be released as `8.2.2-rc1` with the constraint `kibana.version: 8.2.2`. With this constraint, during the development/FF phases this package would be available only for snapshots of Kibana 8.2.2, but not for any previous released version. Once Kibana 8.2.2 is released, there should be a released 8.2.2 package of APM too.

**Comment by mtojek** [comment]
@jsoriano I navigated to this PR from the Package Storage v2 doc.

I'd like to double-check one thing: It won't be possible anymore to consider an existing package a "stable" one, right? 

Currently:

I'm working on `nginx-1.8.0`. I pushed it to the Integrations, promoted it to the staging. I did some testing, it looks fine, let's promote it to production.

With the proposal:

I'm working on the `nginx-1.8.0-prerelease`. Pushed it to the Integrations, promoted it to the staging. I did some testing, it looks fine. To release it as "nginx-1.8.0", I need to create another PR to Integrations and promote it through stages again. Right?

I'm not sure if it's an improvement in terms of developer experience as the package owner has to publish the package twice. I think this will be useful if we also decide to deprecate stages as we talk in the package storage v2 doc.

**Comment by jsoriano** [comment]
> It won't be possible anymore to consider an existing package a "stable" one, right?

With the proposal a package is stable following the semver premises: if its version is >= 1.0.0, and it doesn't include prerelease labels. It doesn't depend on where it is published.

> To release it as "nginx-1.8.0", I need to create another PR to Integrations and promote it through stages again. Right?

Yes, this is one of the parts that made me reluctant of removing the staging repository on a first phase, I see the value of multiple registries or delivery channels for this use case, I talk a bit about this in https://github.com/elastic/package-spec/issues/225#issuecomment-941249614.

> I'm not sure if it's an improvement in terms of developer experience as the package owner has to publish the package twice. I think this will be useful if we also decide to deprecate stages as we talk in the package storage v2 doc.

The improvement would be in removing different options to do similar things. Another improvement is to get rid of the promoting step, that has proven to be confusing for developers, we would only publish packages.
We can go step by step. First removing the release tag, and then later considering if we should also get rid of the multiple registries. My feeling is that we shouldn't need the multiple registries.

Perhaps we have to think about the act of publishing. Merging a change and having a build of the package that can be internally used by the developer team doesn't imply that this package should be made available to the public in any form.

For example, for the case of the nginx package you mention, if the only reason of publishing the prerelease is to do some internal validation, then maybe the package shouldn't have been published to any public registry.
If there are other reasons to release the beta/rc packages, as having broader testing or feedback from the community, then I think that it can make sense to make the additional commit to explicitly approve and declare the final release, and then publish it.
It is also possible that in the last rc package some last-minute minor issue was found but it isn't worth to release another rc, then this change would be included only in the final version. This happens in software following this schema, for example Beats 7.0.0 has changes that weren't included in the last public rc (7.0.0-rc2).

Each developer team might decide about using or not prerelease labels and for what packages and versions.

**Comment by ruflin** [comment]
On my end, I try to stop thinking about a PR as the release mechanism but more an API that a few minutes later I can check, if the release was successful or not. As soon as "publish" is done on a package, it will be released a few minutes later assuming all checks passed.

**Comment by jsoriano** [comment]
After some internal discussions we have decided to keep the `release` tag at the datastream level, so it can be still used to individually tag datastreams or integration tiles as beta or experimental.

**Comment by joshdover** [comment]
> * Eventually snapshot and staging registries may be removed.

Been thinking about this more, and I believe this will result in shipping prerelease versions of packages (which are otherwise stable) to older versions of Kibana unless the `constraint.kibana.version` is set to be >= which Kibana version ends up shipping with the `experimental=true` flag removed from the requests to the registry.

To put this in concrete terms:
- User is on Kibana 8.0, has the Foo 1.2.0 (stable) package installed
- Developer publishes a Foo 1.3.0-dev0 prerelease package to the production registry with `kibana.version: ^8.0.0`
- Kibana 8.0 (which always adds the `experimental=true` flag on requests to the registry) shows the user an update is available.

We'll need some way to enforce that prerelease packages like this that are published to the production registry have their `kibana.version` set to a high enough version level to avoid this problem. Have we thought about how we can enforce this?

**Comment by jsoriano** [comment]
@joshdover yes, I think that Kibana should allow users to choose what to do with prerelease packages, this is why I am proposing the changes in https://github.com/elastic/kibana/issues/122973. As is being commented there, maybe an all-or-nothing toggle is not the ideal solution, because this will prevent discovery of non-GA packages, but we probably want to at least warn users of GA packages when they intend to update to a non-GA version.

But the problem is already there with current implementation, if a developer publishes now a Foo 1.3.0 package, with the `release: beta` label, this is going to be available as an update for users of GA versions of the Foo package (or we have some logic now in Kibana preventing that?).

**Comment by joshdover** [comment]
@jsoriano Definitely agree we need a solution on the Kibana side for future releases, but my concern is about releases that were already shipped. Here's a concrete example of a scenario that I'm concerned about:

- We stop appending the `experimental=true` flag to EPR requests in Kibana 8.3.0 (for example). All prior versions of Kibana are still appending `experimental=true` on requests to EPR.
- A user on 8.1.0 of the Stack has installed the `foo@1.2.0` package which is stable
- The integrations developer for `foo` publishes a `foo@1.3.0-dev1` version to production EPR with `constraints.kibana.version: ^8.0.0` and `release: "ga"`
- The user on 8.1.0 sees an available upgrade for `foo@1.3.0-dev1` and upgrades it. The user now has a prerelease version of a package installed that was previously a stable version.

Please correct me if I'm wrong if this situation wouldn't be possible with the current proposal.

Some potential ideas for fixing this:
- Require that any packages with a prerelease version that are published to production EPR have a minimum `constraints.kibana.version` that matches whichever Kibana version we end up shipping https://github.com/elastic/kibana/issues/122973 in. This would ensure that users on older Kibanas never see prerelease versions of packages that are stable.
- Continue to use release tags for the `experimental` API parameter and add a new URL parameter for the prerelease scheme (`prerelease=true`), in concrete terms:
	- Default search request would only return packages with stable semver version
	- `experimental=true` would return packages with `release: "beta"` or `release: "experimental"` with stable semver versions (still excludes packages with prerelease suffix)
	- `prerelease=beta` would ignore the `release` tag and return packages with `-betaX` prereleases suffix. Similar for `prerelease=dev`, `prerelease=rc`, `prerelease=all`, etc.

**Comment by jsoriano** [comment]
@joshdover thanks for your detailed explanation and the proposals. Please take into account that this situation can already happen now without any change. A developer may release a prerelease version according to semver, and forget to change the `release` tag from `ga` to `beta`. This package would appear as stable in current versions of kibana and users could upgrade to it. One of the main motivations for this proposal is to avoid this kind of incoherences.

We could right now remove the `release` tag from all packages. It is optional and deprecated now, and current package registry API "emulates" it according to the new definition, for current versions of Kibana. This would reduce the chance of finding the situation you describe. A `foo@1.3.0-dev1` package without a `release` tag wouldn't be exposed as GA by the registry, to any version of Kibana.

We can also consider adding an additional validation in the package spec, so it is not possible to have non-ga packages according to semver with `release: ga`, but this could break some of the existing packages that are in corner cases (like [this one](https://github.com/elastic/package-registry/issues/793#issuecomment-1043984198), with `release: ga` but prerelease according to semver). We had an internal thread about these packages, and some of them are going to continue with this incoherence.

I think we agree that anything we do regarding this, should target addressing the incoherences between semver and the `release` tag.

Regarding your proposals:

> * Require that any packages with a prerelease version that are published to production EPR have a minimum `constraints.kibana.version` that matches whichever Kibana version we end up shipping https://github.com/elastic/kibana/issues/122973

I wouldn't like to enforce any kibana version for this, this would discourage the support of broader ranges of versions, something we want to encourage.

> * Default search request would only return packages with stable semver version

This is the approach proposed here, and already implemented in the registry.

> * `experimental=true` would return packages with release: "beta" or release: "experimental" with stable semver versions (still excludes packages with prerelease suffix)

Then packages with prerelease suffixes wouldn't appear on current versions of Kibana, right? I think they should still appear, if not, package developers would need to release different sets of prereleases for the different implementations of Kibana.

In any case I think that the ideal place to place any compatibility logic is here, when `experimental=true` is used, as we are deprecating this parameter and the only purpose to keep it is to keep compatibility with current clients.

> * `prerelease=beta` would ignore the `release` tag and return packages with `-betaX` prereleases suffix. Similar for `prerelease=dev`, `prerelease=rc`, `prerelease=all`, etc.

`prerelease` already ignores the `release` tags (unless `experimental` is also used), but doesn't do any filtering on the prerelease label used. This would be a different feature, right? How would it help here?

**Comment by joshdover** [comment]
> Please take into account that this situation can already happen now without any change. A developer may release a prerelease version according to semver, and forget to change the `release` tag from `ga` to `beta`. This package would appear as stable in current versions of kibana and users could upgrade to it. One of the main motivations for this proposal is to avoid this kind of incoherences.

Yes, it could happen today but is unlikely due to the fact that we have snapshot and staging registries. Whenever we deprecate/remove those, this situation becomes the norm: all prerelease packages (including `dev`) will be shown to users on older Kibana versions.

> > * Require that any packages with a prerelease version that are published to production EPR have a minimum `constraints.kibana.version` that matches whichever Kibana version we end up shipping [[Fleet] Add option to toggle search of prerelease packages kibana#122973](https://github.com/elastic/kibana/issues/122973)
> 
> I wouldn't like to enforce any kibana version for this, this would discourage the support of broader ranges of versions, something we want to encourage.

To be clear, the versions I'm most worried about are the `7.17.x` releases, a version that many customers will use until the EOL date (18+ months from now). I'm less worried about this for users on 8.x releases since they can easily upgrade and likely will, meaning there should be less users on the 8.x train that should receive prerelease packages (because we'll change Kibana's search request in an early 8.x release).

> > * `experimental=true` would return packages with release: "beta" or release: "experimental" with stable semver versions (still excludes packages with prerelease suffix)
> Then packages with prerelease suffixes wouldn't appear on current versions of Kibana, right? I think they should still appear, if not, package developers would need to release different sets of prereleases for the different implementations of Kibana.

Yes that's a good point, let's drop this idea for now.

> `prerelease` already ignores the `release` tags (unless `experimental` is also used), but doesn't do any filtering on the prerelease label used. This would be a different feature, right? How would it help here?

Apologies, I missed that this new flag was already added, had to look at the specific PRs to realize this.

### Problem

I'd like to focus on and agree on the problem before jumping to solutions too quickly. Here's how I see it:
- Today, users get all prerelease versions published to the production EPR.
- In the future, the production registry will not only host 'tech preview' and 'beta' packages, but also 'dev' packages. Though technically these are also prerelease versions and technically this is possible before this change, in practice users do not get dev packages today so this would be new behavior.
- Integration developers and users alike probably do not expect dev packages to be released to users.
- We should prevent dev packages from being shipped to users of a GA product (Fleet is GA)
- However, integration developers still need a way to test dev packages on older Kibana versions before they're released to users.

### Solution

> * Require that any packages with a prerelease version that are published to production EPR have a minimum `constraints.kibana.version` that matches whichever Kibana version we end up shipping [[Fleet] Add option to toggle search of prerelease packages kibana#122973](https://github.com/elastic/kibana/issues/122973) in. This would ensure that users on older Kibanas never see prerelease versions of packages that are stable.

I think we may be able to use some version of this idea to solve this problem, if we do indeed agree it's worth solving. However, it wouldn't be without some drawbacks. Here's what I'm thinking:
1. Require a minimum `constraints.kibana.version` of `^8.3.0` (for example) on any package published to the _production_ registry with a prerelease semver version
2. Integration developers can use the `xpack.fleet.developer.disableRegistryVersionCheck` Kibana config flag to test this package on 7.17.x
3. When publishing the stable version, developers can reduce the `constraints.kibana.version` to `^7.17.0`
4. Do not change the behavior of `experimental=true`

The main drawback here is step (3) since this would need to be something developers remember to do. Alternatively, we could make this behavior automatic. Maybe something like this would work:

1. No changes to `constraints.kibana.version` validation / requirements
2. Update `experimental=true` with this behavior:
  - If no `kibana.version` supplied on the request, use the current behavior (return all prerelease semver packages, ignoring the release tag)
  - If `kibana.version` is supplied on the request, filter out all prerelease semver packages except `-betaX`
3. Developers can then use `xpack.fleet.developer.disableRegistryVersionCheck` Kibana config flag to test this package on 7.17.x while no end users on older Kibanas will get dev packages from the production registry.

**Comment by jsoriano** [comment]
Discussion to discuss about the removal of the staging and snapshot registries: https://github.com/elastic/package-storage/discussions/3666

**Comment by juliaElastic** [comment]
@jsoriano I have a question on deprecating release tag. Are packages going to publish release tag at all going forward? And if so, for how long?
I'm asking because of backward compatibility.
Currently, kibana shows the badge on Integrations UI based on the release tag value (beta/experimental). Let's say that kibana changes the logic to show the badge based on semver instead in 8.x. 
However, older versions of kibana are still relying on release tag, so it would mean all packages would look like ga on the UI (no badge)

<img width="767" alt="image" src="https://user-images.githubusercontent.com/90178898/155297404-d48667f3-4ed2-4246-b1c4-a30cc62dbdbb.png">

**Comment by jsoriano** [comment]
> Are packages going to publish release tag at all going forward? And if so, for how long?

The `release` tag is already marked as deprecated, and optional. Packages can already be shipped without this tag.

For backwards compatibility with new packages without a `release` tag, the package registry fills the gap following semantic versioning, here:
https://github.com/elastic/package-registry/blob/2265fb37a31aad1bbc7201f10af683d46ec8f5f8/packages/package.go#L280-L282

So at the API level, packages without a `release` label are going to continue behaving as if they had one. They will have `release: beta` if they are prereleases according to semver, and `release: ga` otherwise.
When I say _at the API level_ I mean that the content of the package is not changed, that means that it won't contain a `release` label in the manifest. From the tests I did with current versions of kibana, this didn't look like a problem, it seems that `release` is only read from calls to the APIs and not from the manifest (but I may be wrong).

We don't plan to remove this compatibility logic anytime soon, this will likely stay there while there are versions of Kibana using it (we can assume forever).

We also expect that nothing new is built relying on the `release` label, as it is deprecated.

**Comment by juliaElastic** [comment]
@jsoriano
thanks, it makes sense, I'll double check the kibana logic, as you said it might not be a problem then

**Comment by jsoriano** [comment]
Thanks @juliaElastic, please let me know if you find a case where not having the `release` in the manifest can be a problem.

**Comment by joshdover** [comment]
Apologize for the delay, thanks for taking the time to answer these questions, @jsoriano.

> This proposal is mostly about the deprecation of the release tag and the increased use of
semantic versioning as a well-known schema.

Great point. Let's focus on just this change for the registry in general. Thank you for clarifying they are being considered separately.

> there are still the questions about tech preview/beta vs dev packages. In my opinion we shouldn't
do any special handling between them.

A few questions:
- Should we implement the mapping logic in https://github.com/elastic/kibana/issues/126348#issuecomment-1049931152 in the registry so it can be consistent across Kibana and the Integration docs pages?
- Similar to above, should we have share logic for showing beta, but not dev packages to users across Kibana and the integration docs?
- Though we're not removing the staging or snapshot registries in this change, should we have a policy that dev and tech preview packages should not be deployed to production for the time being to avoid the issue of distributing these packages to users of older stack versions?

> We probably need to make a better job differentiating the build of a package from its public release. There can be internal builds of packages that are never published to the public registry.

+1 it would be helpful to have a build number or git sha in addition to a semantic version number, like we do for stack builds

**Comment by juliaElastic** [comment]
> Should we implement the mapping logic in https://github.com/elastic/kibana/issues/126348#issuecomment-1049931152 in the registry so it can be consistent across Kibana and the Integration docs pages?

@joshdover I asked the same question here: https://github.com/elastic/kibana/issues/122973#issuecomment-1054214111

**Comment by joshdover** [comment]
> I don't think we have a policy like this one at the moment and anyone could publish now an experimental package and it would be available for everyone. Has this caused any issue so far?
> 
> We may be afraid of this being more an issue with the long support of 7.17, but other factors make me think that this may not be such a probable issue: Users staying in 7.x are probably not going to do unattended upgrades, or install new packages. New packages are the main candidates to have more unstable technical previews, and developers creating these packages are probably going to target 8.x only.

It has not become an issue so far. Do keep in mind that some internal packages do automatically run package upgrades on Kibana startup as of 7.16.0 (apm, endpoint, synthetics, fleet_server, elastic_agent). Of these, fleet_server and elastic_agent are still using a version constraint that would ship to both 7.16 and 8.0 and endpoint uses a constraint that would ship to 8.0. apm and synthetics seem to bumping their version constraint on each stack release, so those should not be problems.

**Comment by jsoriano** [comment]
Closing this, in principle the only pending change is in Fleet, that is being discussed in https://github.com/elastic/kibana/issues/122973.
