### ISSUE TITLE
[Change Proposal] Introduce a new `Infrastructure` category for integration packages

### ISSUE THREAD

**Issue by osmanis** [elastic/package-spec#381]
Currently the Integrations directory does not provide an easy way to view infrastructure related integrations for monitoring. This makes it challenging for users to easily see integrations related to observability only, without seeing integrations related to search and security use cases. This also makes it difficult to build in-product guidance to help users onboard on to an infrastructure monitoring use case.

**Proposal**: Introduce a new `Infrastructure` category and tag related integration packages accordingly. This would allow the Integrations UI to show and filter based on an `Infrastructure` category. We'll need to determine the scope as to what gets classified  "infrastructure". E.g. tech stack, cloud services, network devices, etc.

cc @jen-huang @pmeresanu85 @akshay-saraswat @LL6688 @mukeshelastic 

PRs for implementation reference:
- https://github.com/elastic/package-spec/pull/366
- https://github.com/elastic/package-registry/pull/841
- https://github.com/elastic/kibana/pull/135758

# Implementation
- [x] Support in package-spec https://github.com/elastic/package-spec/pull/429
- [x] Support in package-registry https://github.com/elastic/package-registry/pull/888
- [x] Support in Fleet https://github.com/elastic/kibana/pull/142115
- [x] Deploy package registry version that has the new category
- [ ] Release package-spec 2.0.0

**Comment by pmeresanu85** [comment]
FYI: @rameshelastic

**Comment by formgeist** [comment]
@jen-huang I'm not familiar with how categories are generated in the Integrations UI. Are they simply dynamic based on the packages available, so if we change the package specs of all the necessary Infrastructure integrations, they will appear in a new Infrastructure category?

**Comment by formgeist** [comment]
@kpollich Thanks for clarifying 

@ManojS-shetty With the clarification above, are you able to move forward with changing the packages relevant for Infrastructure category? cc @rameshelastic @pmeresanu85

**Comment by ManojS-shetty** [comment]
@mtojek @jsoriano  As i have tried adding a package level change and tried to build using elastic-package and it throws me categories validation message. Can we know when the new category `- Infrastructure` will be added? let us know if any inputs needed here.

**Comment by mtojek** [comment]
Manoj, which package are you referring to? AFAIR there is an internal document to validate the idea of introducing a new category. I guess that your PM should take a look at it first.

**Comment by pmeresanu85** [comment]
@jen-huang can you please update us on the progress here, as this issue is critical for our onboarding 2.0? 

What needs to be done is to add the "infrastructure" category in the package spec : https://github.com/elastic/package-spec/blob/main/spec/integration/manifest.spec.yml


FYI: @LL6688

**Comment by mtojek** [comment]
> @jen-huang can you please update us on the progress here, as this issue is critical for our onboarding 2.0?

I understand that it's critical, but we can't simply approve any request for a new category. We would end up with random tags with 1-3 integrations inside. To prevent this situation, Akshay prepared a dedicated [document](https://docs.google.com/document/d/1pMsELVC4XbGXeFsR2gvELk5HLrLaNCujztogRzKjbOU/edit) that provides questions you should answer (and share with other folks) to justify creating the new category.

**Comment by pmeresanu85** [comment]
@osmanis @LL6688 please advise how to proceed here

**Comment by LL6688** [comment]
@osmanis how shall we proceed on this?

**Comment by osmanis** [comment]
> I understand that it's critical, but we can't simply approve any request for a new category. We would end up with random tags with 1-3 integrations inside. To prevent this situation, Akshay prepared a dedicated [document](https://docs.google.com/document/d/1pMsELVC4XbGXeFsR2gvELk5HLrLaNCujztogRzKjbOU/edit) that provides questions you should answer (and share with other folks) to justify creating the new category.

@mtojek I think Akshay's doc was created during this ask so the process for getting a new category wasn't fully defined at the time. So I think that's where some confusion lies. But I had a look at the doc and it seems that the Ecosystem team is required to approve. Do you know who specifically can review and approve?

**Comment by mtojek** [comment]
Akshay prepared the process to let teams submitting new categories perform this exercise and shared their results. As part of the ex-Ecosystem team (@jsoriano, @mrodm, @mtojek), I'd like to see a report answering those questions in terms of the `infrastructure` category. 

ping @jlind23 if I misinterpret something.

**Comment by jlind23** [comment]
@mtojek you are right. There is no a documented to go through.

@osmanis those are the questions that you should answer in order to passe the eligibility requirements:
- New category must group at least 5 integrations
- Alternative existing categories in which these integrations are (currently) or could be (in the future) grouped.
- Proof that this label is a well-known industry vocab and not jargon used by a few
- Usage of the keyword in Gartner or Forrester industry reports
- Competitor blogs using this label or keyword
- Customer interview notes mentioning this keyword
- Proof that users use this label to describe this subset of integrations
- Enhancement requests that complain about the lack of this category
- Full-story data reporting on average 50+ unique searches for this keyword per month in the integrations UI
- Usage of this category for filtering purposes by our competitors or partners
- Impact that are we expecting with this category and how we will measure it (success criteria)

cc @mukeshelastic @nimarezainia

**Comment by pmeresanu85** [comment]
@jlind23 @mukeshelastic @nimarezainia can you provide a sample of a category where the 11 point have been filled out before? Wanted to have a sample before we start.

**Comment by mukeshelastic** [comment]
@mtojek @jlind23  this isn't a general request for adding category for a new set of integrations but associating all observability integrations with this category so that in the trial user workflow, we can replace the recommended integrations at the top of integrations UI, with observability relevant integrations, if the trial user shared their use case as observability. 

So this isn't the general request that we get from integrations authors about expanding category but a more strategic one to provide tailored user experience to observability users in trial user experience.

**Comment by mukeshelastic** [comment]
@pmeresanu85 @osmanis  I stand corrected. Even though the outcome of adding the infrastructure category is slightly different i.e. to update the recommended integrations based on selected category during the trial workflow, the request remains the same, which is to add a new category. 

Thanks @mtojek for the persistent push back to do the right thing and follow the process. 

@pmeresanu85 @osmanis  The process is meant to make the category creation more thoughtful and avoid meaningless categories creation so that the integrations UI users have less confusing integrations browsing experience ( Right now, we have few redundant categories, something @dborodyansky is helping drive to clarity.. more details [here](https://docs.google.com/document/d/1Ha-rqDbMAYIt8KIU-E6dZqU4WyQ0AjbeiY3lKxeP7nc/edit#)  

However the infrastructure category as proposed here, is a common term used in observability industry so don't think it will be much of an effort to answer these questions. I took a stab at the answers because you are amongst the first ones to follow ("threat intel" folks followed it but not exactly as we outlined here) and I do have some infra obs background. 

1. New category must group at least 5 integrations
     - Pretty sure this will happen but feel free to outline 5 integrations.   

2. Alternative existing categories in which these integrations are (currently) or could be (in the future) grouped.
     - OS, containers are probably category that can be combined. Most often infrastructure is synonymously used as compute infrastructure, representing VMs, virtualization technologies, operating systems and container infrastructure. So this is something to keep in mind as I _think_ here we are proposing to bring all observability integrations in infrastructure and I am not sure if that is the right thing to do, as in general infrastructure is seen as compute infrastructure and is perceived differently than say databases or message queues.  A possible all inclusive alternative term is observability. So something to think about.. 

3. Proof that this label is a well-known industry vocab and not jargon used by a few
     - Most common observability vendors use  infrastructure and infrastructure observability extensively. 

4. Proof that Users use this label to describe this subset of integrations
    - I didn't find infrastructure in competitor's integrations catalog
  
5. Impact that are we expecting with this category and how we will measure it
    - This is on us to provide the framework to measure the telemetry on category and keyword search but assuming you had that support, how would you characterize the impact of introducing this category?

**Comment by LL6688** [comment]
From my point of view, we just need to make a decision/suggestion. And we can still change it/revise it later. @mukeshelastic  , can we warp this up in a day or 2? Otherwise, we might miss this..

**Comment by mukeshelastic** [comment]
@LL6688 @osmanis @jen-huang @Michael-Yang-Elastic @kpollich and few others discussed this use case live and the infrastructure category described here accounts for infrastructure observability use case so all of the infrastructure observability integrations will be included in this category. @pmeresanu85 to correct if that isn't the case. 

I believe, we have a good rationale for introducing this category and combining all of the infra obs integrations under it. Also given how ubiquitous the term infrastructure is, in observability products, I am green on introducing this category in integrations catalog.

**Comment by LL6688** [comment]
thank you all!

**Comment by pmeresanu85** [comment]
@ManojS-shetty is there anything outstanding from our side to include the selected integrations in the "infrastructure" category?

**Comment by ManojS-shetty** [comment]
Yes @pmeresanu85 i am testing this by tagging few integration package under the new category. I have few open question before tagging, i will be taking up with the @jsoriano  and keep you posted.

**Comment by ManojS-shetty** [comment]
> Hi @ManojS-shetty and @pmeresanu85 , would learn more about where we are for this issue. And what's left to do, and if there are any more open questions... I just invited Manoj to our weekly sync, hopefully Manoj can attend.. thansk!

Apologies @LL6688 Could not attend the meet as it was india holiday.

Regarding the latest update we have is the package spec changes have been merged and waiting for latest v0.65.0 release of the elastic- package here: [link](https://github.com/elastic/elastic-package/releases/tag/v0.64.0) in order to tag the particular integration under new infrastructure category. I will be following it up today and do what is necessary from our team.

**Comment by LL6688** [comment]
Nice. Many thanks! No worries about the meeting!

Cheers,

Leslie

**Comment by jsoriano** [comment]
Package spec v2.0.0 and elastic package v0.65.0, that includes the version of the spec, have been released. This category should already work locally.

Once https://github.com/elastic/integrations/pull/4387 is merged, it will be also possible to use it in the integrations repository.

**Comment by ManojS-shetty** [comment]
Thank you @jsoriano . I am confirming here that i am able to tag the integrations under `infrastructure` category with elastic-package latest. Once i finish tagging all marked integration will get the PR reviewed and will keep the updates posted.

**Comment by jsoriano** [comment]
https://github.com/elastic/integrations/pull/4387 has been merged, it should be possible to use the `infrastructure` category now.
