### ISSUE TITLE
Add support for runtime fields in packages

### ISSUE THREAD

**Issue by ruflin** [elastic/package-spec#39]
Soon Elasticsearch is planned to support runtime fields: https://github.com/elastic/elasticsearch/issues/59332 I assume these can not be specified currently in our fields.yml. We should add support for these fields in fields.yml and on the Kibana side be able to create the correct Elasticsearch templates and Kibana index patterns.

**Comment by ruflin** [comment]
@ycombinator for the spec
@skh @neptunian For awareness for the template / index pattern creation
@ph For awareness
@andresrc We should figure out if and where we want to use this in packages in the future.

**Comment by ruflin** [comment]
Adding to this, Elasticsearch supports to set the `dynamic: runtime`: https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html A package dev should be able to select this option as the default for dynamic fields. APM asked for this in the context of the apm package defaults (@simitt ).

**Comment by simitt** [comment]
@elastic/apm-server feel free to pick this up for `7.15`

**Comment by ruflin** [comment]
We would really like to see this prioritised. The way I would propose this to be implemented is as following:

```
    - name: foo.bar
      type: long
      runtime: true
```

This is slightly different from the way it [looks in Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/runtime-mapping-fields.html) where a separate block for runtime fields has to be specified. Having it directly as a boolean in the fields definition allows a very simple way to enable / disable it for devs. Fleet still has to create the additional block.

**Comment by amitkanfer** [comment]
@jlind23 putting this on your radar.

**Comment by joshdover** [comment]
A couple things to consider here. Runtime fields is mostly optimized for extracting new fields out of other indexed fields that are available in the "doc values" and the runtime field's script has to be written differently depend on whether or not the field that we're extracting from is being indexed. So there's really 2 use cases here:

- Runtime fields that have supply a custom script to extract data from another _indexed_ field
- Runtime fields that simply populate a value from `_source` that is not indexed
	- This is the use case that is covered by @ruflin's comment in https://github.com/elastic/package-spec/issues/39#issuecomment-1363711624

When Fleet creates the index templates for runtime fields, the `script` field for a runtime field will need to differ based on whether or not the field is indexed. If `index: false` is specified or the field is not mapped at all, the field will not be available in `doc['foo']` but will be available in `params._source['foo']`.

We can probably support a design like this for both use cases:
```
- name: foo.bar
  type: long
  runtime: true
- name: foo.baz
  type: long
  runtime: |
    doc['message'].value().doSomething()
```

I think the implementation could work something like this:
- If `runtime` is a boolean `true`, then create a runtime script with `params._source['<field>']`
- If `runtime` is a string, just use that for the script directly

**Comment by jsoriano** [comment]
Plan sounds good to me too.

> If `runtime` is a boolean `true`, then create a runtime script with `params._source['<field>']`

This seems to be already the behaviour of Elasticsearch when no script is set (see [here](https://www.elastic.co/guide/en/elasticsearch/reference/8.7/runtime-mapping-fields.html#runtime-fields-scriptless)). In principle it seems enough to add the field as runtime field, without any script, and it does the equivalent to `params._source['<field>']`.

> Fleet should also add support to create those runtime fields

@mrodm could you please check if there is already an open issue for that, and create one otherwise?

> do you foresee any issue having that field being `boolean` or `string` for fleet?

It seems possible to have variables with multiple types in typescript, I think this will need more special handling in Go if we need to do something with this field :slightly_smiling_face: 

> * could it be checked previously @jsoriano ?

Maybe we can try to remove a field in a package, and add it as a runtime field in the `index_template` configuration of its manifest. Then check what system tests do, and what sample documents they generate.

**Comment by kpollich** [comment]
> Fleet should also add support to create those runtime fields, @kpollich do you foresee any issue having that field being boolean or string for fleet?

I don't foresee this being an issue on Fleet's end. Just a small piece of logic for how the field is used when generating mappings.

**Comment by mrodm** [comment]
> Maybe we can try to remove a field in a package, and add it as a runtime field in the index_template configuration of its manifest. Then check what system tests do, and what sample documents they generate.

I've tested this approach, and what I observed is that runtime fields are just present in the `fields` in the documents instead of `_source`. As it is indicated [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/runtime.html):

> Use the fields parameter on the _search API to retrieve the values of runtime fields. Runtime fields won’t display in _source, but the fields API works for all fields, even those that were not sent as part of the original _source.

In that case, `elastic-package` should also take into account the `fields` from the documents retrieved from Elasticsearch to validate the fields defined in the package.

Created issue to support runtime fields in elastic-package https://github.com/elastic/elastic-package/issues/1229

Also tested that if nowadays a field with the `runtime` key is added into a package, this is not going to fail and it will just add a new mapping with the given type. Because of that, it is also needed to add a new validation rule in package-spec to ensure a minimum Kibana version (8.8 ? 8.9?)

**Comment by jen-huang** [comment]
Thanks @mrodm for the work here so far. I'm going to move this issue to Sprint 12 but of course it could get closed out by https://github.com/elastic/package-spec/pull/505 if that merges soon. Follow up issues https://github.com/elastic/elastic-package/issues/1229, https://github.com/elastic/kibana/issues/155255) will be moved to Sprint 12 as well.

**Comment by jlind23** [comment]
@mrodm @jsoriano what is missing here as we have merged https://github.com/elastic/package-spec/pull/505 ?

**Comment by mrodm** [comment]
> @mrodm @jsoriano what is missing here as we have merged #505 ?

The support for package-spec has been added through that PR, but runtime fields need to be supported also in Kibana/Fleet. There is another issue for that https://github.com/elastic/kibana/issues/155255. According to the comments in the PR, it should be for 8.9.0 https://github.com/elastic/package-spec/pull/505/files#r1173839069

Should we close this one and just let the other issue in kibana open ? @jlind23

**Comment by ruflin** [comment]
We should not close this issue. This is about adding support fo runtime fields in packages. As long as Fleet does not support it, it is from my perspective not supported in packages even though users could add it.

**Comment by jlind23** [comment]
@mrodm moving this issue out of our current sprint as they are is nothing to do here from a package-spec perspective. We will close this one later as ruflin stated as soon as https://github.com/elastic/kibana/issues/155255 is fixed.
