### ISSUE TITLE
[Change Proposal] Add flag to hide "parent tile" in integrations UI for integrations with multiple policy templates

### ISSUE THREAD

**Issue by kpollich** [elastic/package-spec#802]
For integrations like `elastic_connectors`, usage of of `policy_templates` is more about easing maintenance burden and less about reusing variables across different templates or leveraging any kind of information architecture. For integrations like this, we should have an option/flag in the manifest that allows Fleet to hide the "parent tile" for the integration, instead _only_ showing the policy templates cards.

**Comment by kpollich** [comment]
cc @seanstory

**Comment by jsoriano** [comment]
Makes sense 👍 I think this could have been used even in some packages that have many policies now, like AWS.

I would only avoid focusing on representation and call the flag something like `disable_parent_policy`, or something like this.

**Comment by kpollich** [comment]
Something else to note when it comes to supporting this in Fleet - perhaps we should use the policy template name when populating the integration policy's name field. Today creating an "AWS Billing Metrics" integration policy still results in an integration policy named "aws-1" and editing it takes you to the full integration policy page for all policy templates.

**Comment by seanstory** [comment]
> perhaps we should use the policy template name when populating the integration policy's name field.

+1. I'm anticipating customer confusion about `connectors_1`, `connectors_2` instead of `github_connector_1`, `gdrive_connector_1`. We can prepare for that with documentation and signposting, but if y'all can help us pre-empt it, that's even better. ❤

**Comment by jen-huang** [comment]
Some packages have the opposite problem, where _only_ the parent tile should be shown even if there are multiple policy templates. We do this manually in the code for `kubernetes` package in Fleet: [Remove Kubernetes package granularity](https://github.com/elastic/kibana/blob/e5b0b8108b392dae070b87175cf2d43522576c4d/x-pack/plugins/fleet/public/applications/integrations/sections/epm/screens/home/hooks/use_available_packages.tsx#L140).

It may make sense for this flag to be enum rather than boolean, for example `policy_behavior: 'parent_only' | 'children_only' | 'default'`. `default` or unset value would mean the current behavior of showing both parent and children policy templates.

**Comment by mrodm** [comment]
Created issue to expose `policy_templates_behavior` field in EPR endpoints:
https://github.com/elastic/package-registry/issues/1243

**Comment by jen-huang** [comment]
@mrodm Could you also create a Kibana issue to support this new field? Thanks!

**Comment by mrodm** [comment]
> [@mrodm](https://github.com/mrodm) Could you also create a Kibana issue to support this new field? Thanks!

@jen-huang Sure! Issue created in Kibana https://github.com/elastic/kibana/issues/198145
